source "https://supermarket.chef.io"

metadata

cookbook "beanstalkd"
cookbook "mysql", "~> 5.6"
cookbook "nginx", "~> 2.6"
cookbook "php"
cookbook "php-fpm", git: "https://github.com/yevgenko/cookbook-php-fpm.git"
cookbook "composer", git: "https://github.com/escapestudios-cookbooks/composer.git"
cookbook "memcached"